backbone:
  OS: 8
  bn_d: 0.05
  dropout: 0.02
  extra:
    shallow_feats: true
    width_mult: 1.0
  name: mobilenetv2
  train: true
dataset:
  color_map:
    0:
    - 0
    - 0
    - 0
    1:
    - 170
    - 170
    - 170
    2:
    - 0
    - 250
    - 0
    3:
    - 51
    - 102
    - 102
    4:
    - 255
    - 120
    - 0
    5:
    - 60
    - 20
    - 220
    6:
    - 0
    - 60
    - 0
    7:
    - 220
    - 20
    - 60
  img_means:
  - 0.32468202
  - 0.35106816
  - 0.31316271
  img_prop:
    depth: 3
    height: 512
    width: 1024
  img_stds:
  - 0.23319099
  - 0.22611748
  - 0.22684037
  labels:
    0: obstacle
    1: road
    2: grass
    3: vegetation
    4: sky
    5: human
    6: tree
    7: animal
  labels_w:
    0: 2.50650793
    1: 3.51780355
    2: 32.4134528
    3: 7.82088362
    4: 20.11303016
    5: 12.67862677
    6: 50.0949722
    7: 50.49834979
  location: /media/christoph/1TB/rasenmaeherset/small
  name: cityscapes
  workers: 3
decoder:
  bn_d: 0.05
  dropout: 0.02
  extra:
    aspp_channels: 32
    last_channels: 16
  name: aspp_progressive
  train: true
head:
  dropout: 0.1
  name: segmentation
train:
  avg_N: 3
  batch_size: 7
  crop_prop:
    height: 512
    width: 512
  down_epochs: 60
  final_decay: 0.995
  loss: xentropy
  max_epochs: 300
  max_lr: 0.05
  max_momentum: 0.9
  min_lr: 0.01
  min_momentum: 0.85
  report_batch: 1
  report_epoch: 1
  save_imgs: true
  save_summary: false
  up_epochs: 0.5
  w_decay: 0.0005
